## Part 2. A Little More of a Challenge... ##

1. 3 will be printed to the console because "i" gets incremented to 3 before the last loop iteration.
2. 150 will be printed to the console because in the last iteration of the loop "discountedPrice" get set to 150.
3. 150 will be printed to the console because in the last iteration of the loop "finalPrice" get set to 150.
4. The array [50, 100, 150] will be returned because those are the values that get pushed to the "discounted" array in each iteration of the loop.
5. An error is returned because "i" is declared with let and the function call on line 12 is outside of the code block where "i" was declared.
6. An error is returned because "discountedPrice" is declared with let and the function call on line 13 is outside of the code block where "discountedPrice" was declared.
7. 150 will be returned because "finalPrice" is declared with let and the function call on line 14 is inside of the code block where "finalPrice" was declared.
8. The array [50, 100, 150] will be returned because "discounted" is declared with let and the return call is inside of the code block where "discounted" was declared.
9. An error is returned because "i" is declared with const and the function call on line 12 is outside of the code block where "i" was declared.
10. 3 will be printed to the console because "length" is declared with const and the function call on line 13 is inside of the code block where "length: was declared.
11. The array [50, 100, 150] will be returned because "discounted" is declared with const and the return call is inside of the code block where "discounted" was declared. Also the variable identifier is not being reassigned.

12A. student.name
12B. student['Grad Year']
12C. student.greeting()
12D. student['Favorite Teacher'].name
12E. student.courseLoad[0]
